//routes to link API
export var __apiURLUser ="http://localhost:3003/user/";
export var __apiURLCategory ="http://localhost:3003/category/";
export var __apiURLDocument ="http://localhost:3003/document/"
export var __apiURLVehicle ="http://localhost:3003/vehicle/";
export var __apiURLState ="http://localhost:3003/state/";
export var __apiURLCity ="http://localhost:3003/city/";
export var __apiURLCountry ="http://localhost:3003/country/";
export var __apiURLListing ="http://localhost:3003/listing/";
export var __apiURLSegment ="http://localhost:3003/segment/";